 const originalQuestions = [
        // Biology (90 MCQs)
        { "question": "What is the primary structure of a virus?", "options": ["Double-stranded DNA", "Protein coat and genetic material", "Cell wall and membrane", "Mitochondria"], "correctAnswer": 1 },
        { "question": "Which disease is caused by HIV?", "options": ["Tuberculosis", "AIDS", "Malaria", "Hepatitis"], "correctAnswer": 1 },
        { "question": "What is the main source of energy in cellular respiration?", "options": ["Proteins", "Fats", "Glucose", "Water"], "correctAnswer": 2 },
        { "question": "Which of the following is a monosaccharide?", "options": ["Starch", "Glucose", "Cellulose", "Glycogen"], "correctAnswer": 1 },
        { "question": "What property of water allows it to act as a solvent?", "options": ["Density", "Polarity", "Cohesion", "Specific heat"], "correctAnswer": 1 },
        { "question": "Which organelle is known as the powerhouse of the cell?", "options": ["Nucleus", "Mitochondria", "Endoplasmic reticulum", "Golgi apparatus"], "correctAnswer": 1 },
        { "question": "What is the function of ribosomes?", "options": ["Protein synthesis", "Lipid storage", "DNA replication", "ATP production"], "correctAnswer": 0 },
        { "question": "Which part of the neuron receives signals?", "options": ["Axon", "Dendrites", "Myelin sheath", "Cell body"], "correctAnswer": 1 },
        { "question": "What is the role of enzymes in reactions?", "options": ["Increase activation energy", "Act as catalysts", "Store energy", "Break down water"], "correctAnswer": 1 },
        { "question": "Which theory explains natural selection?", "options": ["Lamarckism", "Darwinism", "Mendel’s Laws", "Watson-Crick Model"], "correctAnswer": 1 },
        { "question": "What hormone regulates the menstrual cycle?", "options": ["Insulin", "Estrogen", "Adrenaline", "Thyroxine"], "correctAnswer": 1 },
        { "question": "Which type of joint allows the widest range of motion?", "options": ["Hinge", "Ball and socket", "Pivot", "Gliding"], "correctAnswer": 1 },
        { "question": "What is the genetic material of most organisms?", "options": ["RNA", "DNA", "Protein", "Lipid"], "correctAnswer": 1 },
        { "question": "Which blood vessel carries oxygenated blood from the lungs?", "options": ["Pulmonary artery", "Pulmonary vein", "Aorta", "Vena cava"], "correctAnswer": 1 },
        { "question": "What is the main function of the lymphatic system?", "options": ["Oxygen transport", "Immune response", "Nutrient absorption", "Waste excretion"], "correctAnswer": 1 },
        { "question": "Which process involves gas exchange in the lungs?", "options": ["Digestion", "Respiration", "Circulation", "Excretion"], "correctAnswer": 1 },
        { "question": "What is the primary function of the kidney?", "options": ["Digestion", "Excretion", "Respiration", "Circulation"], "correctAnswer": 1 },
        { "question": "Which molecule is a conjugated molecule?", "options": ["Glucose", "Glycoprotein", "Starch", "Lipid"], "correctAnswer": 1 },
        { "question": "What is the mode of transmission of AIDS?", "options": ["Air", "Blood and bodily fluids", "Water", "Food"], "correctAnswer": 1 },
        { "question": "Which enzyme breaks down proteins in the stomach?", "options": ["Amylase", "Pepsin", "Lipase", "Trypsin"], "correctAnswer": 1 },
        { "question": "What is the function of the cerebellum?", "options": ["Controls breathing", "Coordinates movement", "Regulates heartbeat", "Processes vision"], "correctAnswer": 1 },
        { "question": "Which nitrogenous waste is excreted by humans?", "options": ["Ammonia", "Urea", "Uric acid", "All of these"], "correctAnswer": 1 },
        { "question": "What is the result of crossing over in meiosis?", "options": ["Identical chromosomes", "Genetic variation", "No change", "Cell division"], "correctAnswer": 1 },
        { "question": "Which organ produces insulin?", "options": ["Liver", "Pancreas", "Kidney", "Spleen"], "correctAnswer": 1 },
        { "question": "What is the primary source of energy for muscles?", "options": ["Glucose", "Fat", "Protein", "Vitamins"], "correctAnswer": 0 },
        { "question": "Which disease is caused by a deficiency of vitamin C?", "options": ["Rickets", "Scurvy", "Beri-beri", "Night blindness"], "correctAnswer": 1 },
        { "question": "What is the function of the Golgi apparatus?", "options": ["Protein synthesis", "Lipid storage", "Modification of proteins", "ATP production"], "correctAnswer": 2 },
        { "question": "Which blood group is known as the universal donor?", "options": ["A", "B", "AB", "O"], "correctAnswer": 3 },
        { "question": "What is the effect of smoking on the respiratory system?", "options": ["Improves lung capacity", "Causes lung cancer", "Increases oxygen intake", "Strengthens alveoli"], "correctAnswer": 1 },
        { "question": "Which part of the brain controls voluntary movements?", "options": ["Cerebellum", "Cerebrum", "Medulla", "Thalamus"], "correctAnswer": 1 },
        { "question": "What is the role of DNA polymerase?", "options": ["Translates RNA", "Synthesizes DNA", "Breaks down proteins", "Produces energy"], "correctAnswer": 1 },
        { "question": "Which process regulates body temperature?", "options": ["Osmoregulation", "Thermoregulation", "Excretion", "Digestion"], "correctAnswer": 1 },
        { "question": "What is the function of hemoglobin?", "options": ["Oxygen transport", "Enzyme production", "Lipid storage", "DNA replication"], "correctAnswer": 0 },
        { "question": "Which organelle contains chlorophyll?", "options": ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"], "correctAnswer": 1 },
        { "question": "What is the cause of hemophilia?", "options": ["Bacterial infection", "Genetic mutation", "Viral infection", "Nutritional deficiency"], "correctAnswer": 1 },
        { "question": "Which phase of the cardiac cycle involves ventricular contraction?", "options": ["Diastole", "Systole", "Atrial contraction", "Relaxation"], "correctAnswer": 1 },
        { "question": "What is the primary function of the small intestine?", "options": ["Water absorption", "Nutrient absorption", "Gas exchange", "Blood filtration"], "correctAnswer": 1 },
        { "question": "Which type of muscle is involuntary?", "options": ["Skeletal", "Cardiac", "Smooth", "All of these"], "correctAnswer": 2 },
        { "question": "What is the role of antibodies in the immune system?", "options": ["Fight infections", "Store energy", "Transport oxygen", "Produce hormones"], "correctAnswer": 0 },
        { "question": "Which gas is produced during photosynthesis?", "options": ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "correctAnswer": 1 },
        { "question": "What is the function of the alveoli?", "options": ["Filter blood", "Exchange gases", "Produce enzymes", "Store urine"], "correctAnswer": 1 },
        { "question": "Which process involves the movement of water across a semipermeable membrane?", "options": ["Diffusion", "Osmosis", "Active transport", "Phagocytosis"], "correctAnswer": 1 },
        { "question": "What is the result of a mutation in DNA?", "options": ["No change", "Genetic variation", "Improved function", "Cell death"], "correctAnswer": 1 },
        { "question": "Which organ regulates blood sugar levels?", "options": ["Liver", "Pancreas", "Kidney", "Heart"], "correctAnswer": 1 },
        { "question": "What is the primary function of the epidermis in plants?", "options": ["Photosynthesis", "Protection", "Water transport", "Food storage"], "correctAnswer": 1 },
        { "question": "Which vitamin is fat-soluble?", "options": ["Vitamin C", "Vitamin D", "Vitamin B12", "Folic acid"], "correctAnswer": 1 },
        { "question": "What is the function of the nucleolus?", "options": ["Protein synthesis", "Ribosome production", "DNA storage", "Lipid synthesis"], "correctAnswer": 1 },
        { "question": "Which process involves the uptake of large particles by a cell?", "options": ["Pinocytosis", "Phagocytosis", "Osmosis", "Diffusion"], "correctAnswer": 1 },
        { "question": "What is the role of the thymus gland?", "options": ["Produces hormones", "Matures T-lymphocytes", "Filters blood", "Stores fat"], "correctAnswer": 1 },
        { "question": "Which blood component is responsible for clotting?", "options": ["Red blood cells", "White blood cells", "Platelets", "Plasma"], "correctAnswer": 2 },
        { "question": "What is the primary source of energy for plants?", "options": ["Water", "Sunlight", "Carbon dioxide", "Minerals"], "correctAnswer": 1 },
        { "question": "Which organelle is involved in detoxification?", "options": ["Lysosome", "Peroxisome", "Endoplasmic reticulum", "Golgi apparatus"], "correctAnswer": 2 },
        { "question": "What is the effect of high temperature on enzyme activity?", "options": ["Increases activity", "Decreases activity", "No effect", "Stops activity"], "correctAnswer": 1 },
        { "question": "Which part of the eye contains photoreceptors?", "options": ["Cornea", "Retina", "Lens", "Iris"], "correctAnswer": 1 },
        { "question": "What is the function of the diaphragm in breathing?", "options": ["Filters air", "Expands chest cavity", "Produces sound", "Circulates blood"], "correctAnswer": 1 },
        { "question": "Which hormone stimulates the fight or flight response?", "options": ["Insulin", "Adrenaline", "Cortisol", "Thyroxine"], "correctAnswer": 1 },
        { "question": "What is the primary function of the large intestine?", "options": ["Nutrient absorption", "Water absorption", "Gas exchange", "Enzyme production"], "correctAnswer": 1 },
        { "question": "Which type of inheritance is hemophilia an example of?", "options": ["Autosomal dominant", "X-linked recessive", "Codominant", "Polygenic"], "correctAnswer": 1 },
        { "question": "What is the role of the pituitary gland?", "options": ["Regulates metabolism", "Controls other glands", "Filters blood", "Produces bile"], "correctAnswer": 1 },
        { "question": "Which process releases energy in cells?", "options": ["Photosynthesis", "Cellular respiration", "Osmosis", "Diffusion"], "correctAnswer": 1 },
        { "question": "What is the function of the myelin sheath?", "options": ["Insulates nerve fibers", "Produces energy", "Transports oxygen", "Synthesizes proteins"], "correctAnswer": 0 },
        { "question": "Which gas is essential for the process of respiration?", "options": ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"], "correctAnswer": 1 },
        { "question": "What is the role of the spleen?", "options": ["Produces insulin", "Filters blood", "Regulates temperature", "Stores urine"], "correctAnswer": 1 },
        { "question": "Which organelle is responsible for autophagy?", "options": ["Mitochondria", "Lysosome", "Nucleus", "Ribosome"], "correctAnswer": 1 },
        { "question": "What is the effect of a low pH on enzyme activity?", "options": ["Increases activity", "Decreases activity", "No effect", "Destroys enzyme"], "correctAnswer": 1 },
        { "question": "Which part of the nephron filters blood?", "options": ["Loop of Henle", "Glomerulus", "Collecting duct", "Proximal tubule"], "correctAnswer": 1 },
        { "question": "What is the primary function of the trachea?", "options": ["Filters air", "Transports air", "Produces mucus", "Exchanges gases"], "correctAnswer": 1 },
        { "question": "Which vitamin is essential for blood clotting?", "options": ["Vitamin A", "Vitamin K", "Vitamin E", "Vitamin D"], "correctAnswer": 1 },
        { "question": "What is the role of the pancreas in digestion?", "options": ["Produces bile", "Releases digestive enzymes", "Filters blood", "Absorbs water"], "correctAnswer": 1 },
        { "question": "Which process involves the splitting of water molecules in photosynthesis?", "options": ["Calvin cycle", "Photolysis", "Glycolysis", "Krebs cycle"], "correctAnswer": 1 },
        { "question": "What is the function of the adrenal glands?", "options": ["Regulates sugar", "Produces stress hormones", "Filters blood", "Stores fat"], "correctAnswer": 1 },
        { "question": "Which type of cell division produces gametes?", "options": ["Mitosis", "Meiosis", "Binary fission", "Budding"], "correctAnswer": 1 },
        { "question": "What is the role of the placenta?", "options": ["Filters blood", "Nourishes fetus", "Produces hormones", "Both b and c"], "correctAnswer": 3 },
        { "question": "Which organelle is involved in lipid synthesis?", "options": ["Nucleus", "Endoplasmic reticulum", "Mitochondria", "Golgi apparatus"], "correctAnswer": 1 },
        { "question": "What is the effect of dehydration on the body?", "options": ["Increases blood volume", "Decreases blood volume", "No effect", "Improves digestion"], "correctAnswer": 1 },
        { "question": "Which part of the brain controls balance?", "options": ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"], "correctAnswer": 1 },
        { "question": "What is the primary function of the urethra?", "options": ["Filters blood", "Transports urine", "Produces enzymes", "Absorbs water"], "correctAnswer": 1 },
        { "question": "Which process involves the conversion of glucose to pyruvate?", "options": ["Glycolysis", "Krebs cycle", "Electron transport", "Calvin cycle"], "correctAnswer": 0 },
        { "question": "What is the role of the thyroid gland?", "options": ["Regulates metabolism", "Produces insulin", "Filters blood", "Stores calcium"], "correctAnswer": 0 },
        { "question": "Which type of bond holds the base pairs in DNA?", "options": ["Covalent", "Hydrogen", "Ionic", "Peptide"], "correctAnswer": 1 },
        { "question": "What is the function of the bronchi?", "options": ["Exchange gases", "Transport air", "Produce mucus", "Filter blood"], "correctAnswer": 1 },
        { "question": "Which mineral is essential for bone health?", "options": ["Iron", "Calcium", "Sodium", "Potassium"], "correctAnswer": 1 },
        { "question": "What is the role of the hypothalamus?", "options": ["Controls hunger", "Regulates temperature", "Both a and b", "Produces bile"], "correctAnswer": 2 },
        { "question": "Which process involves the removal of metabolic wastes?", "options": ["Respiration", "Excretion", "Digestion", "Circulation"], "correctAnswer": 1 },
        { "question": "What is the function of the seminal vesicles?", "options": ["Produce sperm", "Provide nutrients to sperm", "Filter blood", "Regulate hormones"], "correctAnswer": 1 },
        { "question": "Which organelle is involved in protein folding?", "options": ["Ribosome", "Endoplasmic reticulum", "Mitochondria", "Lysosome"], "correctAnswer": 1 },
        { "question": "What is the effect of a high-fat diet on the body?", "options": ["Increases energy", "Causes obesity", "Improves vision", "Enhances immunity"], "correctAnswer": 1 },
        { "question": "Which part of the ear contains the cochlea?", "options": ["Outer ear", "Middle ear", "Inner ear", "Auditory canal"], "correctAnswer": 2 },
        { "question": "What is the role of the liver in metabolism?", "options": ["Produces insulin", "Detoxifies blood", "Regulates heartbeat", "Stores oxygen"], "correctAnswer": 1 },
        { "question": "Which process involves the synthesis of proteins?", "options": ["Translation", "Transcription", "Replication", "Mutation"], "correctAnswer": 0 },
        { "question": "What is the function of the salivary glands?", "options": ["Produce bile", "Secrete saliva", "Filter blood", "Absorb water"], "correctAnswer": 1 },
        { "question": "Which type of immunity is acquired through vaccination?", "options": ["Innate", "Adaptive", "Passive", "Active"], "correctAnswer": 3 },
        { "question": "What is the role of the gallbladder?", "options": ["Produces bile", "Stores bile", "Filters blood", "Regulates sugar"], "correctAnswer": 1 },
        { "question": "Which organelle contains hydrolytic enzymes?", "options": ["Mitochondria", "Lysosome", "Nucleus", "Ribosome"], "correctAnswer": 1 },
        { "question": "What is the effect of exercise on muscles?", "options": ["Weakens muscles", "Strengthens muscles", "No effect", "Reduces size"], "correctAnswer": 1 },
        { "question": "Which part of the kidney filters blood?", "options": ["Ureter", "Nephron", "Bladder", "Urethra"], "correctAnswer": 1 },
        { "question": "What is the role of the parathyroid gland?", "options": ["Regulates calcium", "Produces insulin", "Filters blood", "Stores fat"], "correctAnswer": 0 },
        { "question": "Which process involves the breakdown of fats?", "options": ["Lipolysis", "Glycolysis", "Krebs cycle", "Calvin cycle"], "correctAnswer": 0 },
        { "question": "What is the function of the ciliary muscles?", "options": ["Focus the lens", "Protect the eye", "Produce tears", "Regulate light"], "correctAnswer": 0 },
        { "question": "Which vitamin prevents rickets?", "options": ["Vitamin A", "Vitamin D", "Vitamin E", "Vitamin K"], "correctAnswer": 1 },
        { "question": "What is the role of the appendix?", "options": ["Digests food", "Stores bacteria", "Filters blood", "Produces enzymes"], "correctAnswer": 1 },
        { "question": "Which process involves the movement of ions against a concentration gradient?", "options": ["Diffusion", "Active transport", "Osmosis", "Facilitated diffusion"], "correctAnswer": 1 },
        { "question": "What is the function of the fallopian tubes?", "options": ["Produce eggs", "Transport eggs", "Filter blood", "Store urine"], "correctAnswer": 1 },
        { "question": "Which organelle is involved in cellular respiration?", "options": ["Nucleus", "Mitochondria", "Golgi apparatus", "Lysosome"], "correctAnswer": 1 },
        { "question": "What is the effect of a high-sugar diet?", "options": ["Improves health", "Causes diabetes", "Enhances immunity", "Increases strength"], "correctAnswer": 1 },
        { "question": "Which part of the heart pumps blood to the lungs?", "options": ["Left atrium", "Right ventricle", "Left ventricle", "Right atrium"], "correctAnswer": 1 },
        { "question": "What is the role of the medulla oblongata?", "options": ["Controls movement", "Regulates heartbeat", "Processes vision", "Stores memory"], "correctAnswer": 1 },
        { "question": "Which process involves the synthesis of ATP?", "options": ["Photosynthesis", "Oxidative phosphorylation", "Glycolysis", "Calvin cycle"], "correctAnswer": 1 },
        { "question": "What is the function of the prostate gland?", "options": ["Produces sperm", "Secrete fluid for semen", "Filters blood", "Regulate hormones"], "correctAnswer": 1 },
        { "question": "Which type of cell has a cell wall?", "options": ["Animal cell", "Plant cell", "Bacterial cell", "Both b and c"], "correctAnswer": 3 },
        { "question": "What is the role of the pineal gland?", "options": ["Regulates sleep", "Produces insulin", "Filters blood", "Stores fat"], "correctAnswer": 0 },
        { "question": "Which process involves the uptake of liquid by a cell?", "options": ["Phagocytosis", "Pinocytosis", "Exocytosis", "Osmosis"], "correctAnswer": 1 },

        // Chemistry (50 MCQs)
        { "question": "What is the mole ratio used for in stoichiometric problems?", "options": ["Balancing equations", "Conversion factors", "Measuring temperature", "Determining pressure"], "correctAnswer": 1 },
        { "question": "Which law states that pressure and volume are inversely proportional?", "options": ["Charles's Law", "Boyle's Law", "Avogadro's Law", "Ideal Gas Law"], "correctAnswer": 1 },
        { "question": "What is the standard temperature at STP?", "options": ["0°C", "25°C", "100°C", "-273°C"], "correctAnswer": 0 },
        { "question": "Which element is in Group I of the periodic table?", "options": ["Oxygen", "Sodium", "Chlorine", "Nitrogen"], "correctAnswer": 1 },
        { "question": "What is the shape of a water molecule due to hydrogen bonding?", "options": ["Linear", "Tetrahedral", "Bent", "Trigonal planar"], "correctAnswer": 2 },
        { "question": "What is the unit of the gas constant R?", "options": ["J/mol·K", "L/mol", "atm·L/mol·K", "Both a and c"], "correctAnswer": 3 },
        { "question": "Which factor affects the rate of a chemical reaction?", "options": ["Catalyst", "Color", "Odor", "Texture"], "correctAnswer": 0 },
        { "question": "What is the product of the Haber process?", "options": ["Ammonia", "Nitrogen", "Hydrogen", "Oxygen"], "correctAnswer": 0 },
        { "question": "Which bond is stronger, sigma or pi?", "options": ["Sigma", "Pi", "Both are equal", "Depends on the molecule"], "correctAnswer": 0 },
        { "question": "What is the oxidation number of oxygen in most compounds?", "options": ["+2", "-2", "+1", "-1"], "correctAnswer": 1 },
        { "question": "What is the shape of a molecule with sp3 hybridization?", "options": ["Linear", "Tetrahedral", "Trigonal planar", "Octahedral"], "correctAnswer": 1 },
        { "question": "Which gas law relates volume and temperature at constant pressure?", "options": ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Ideal Gas Law"], "correctAnswer": 1 },
        { "question": "What is the pH of a neutral solution?", "options": ["1", "7", "14", "0"], "correctAnswer": 1 },
        { "question": "Which element has the highest electronegativity?", "options": ["Oxygen", "Fluorine", "Chlorine", "Nitrogen"], "correctAnswer": 1 },
        { "question": "What is the product of the reaction between an acid and a base?", "options": ["Salt and water", "Carbon dioxide", "Hydrogen", "Oxygen"], "correctAnswer": 0 },
        { "question": "Which type of reaction releases heat?", "options": ["Endothermic", "Exothermic", "Catalytic", "Neutral"], "correctAnswer": 1 },
        { "question": "What is the molecular geometry of CO2?", "options": ["Linear", "Bent", "Tetrahedral", "Trigonal pyramidal"], "correctAnswer": 0 },
        { "question": "Which compound is an alkane?", "options": ["C2H4", "C2H6", "C2H2", "C6H6"], "correctAnswer": 1 },
        { "question": "What is the role of a catalyst in a reaction?", "options": ["Increases activation energy", "Lowers activation energy", "Changes products", "Absorbs heat"], "correctAnswer": 1 },
        { "question": "Which gas is produced during the thermal decomposition of limestone?", "options": ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], "correctAnswer": 1 },
        { "question": "What is the oxidation state of chromium in K2Cr2O7?", "options": ["+2", "+6", "+3", "+4"], "correctAnswer": 1 },
        { "question": "Which functional group is present in aldehydes?", "options": ["-OH", "-CHO", "-COOH", "-NH2"], "correctAnswer": 1 },
        { "question": "What is the general formula for alkanes?", "options": ["CnH2n", "CnH2n+2", "CnH2n-2", "CnHn"], "correctAnswer": 1 },
        { "question": "Which acid is present in vinegar?", "options": ["Citric acid", "Acetic acid", "Lactic acid", "Hydrochloric acid"], "correctAnswer": 1 },
        { "question": "What is the product of the reaction between an alcohol and a carboxylic acid?", "options": ["Ester", "Ether", "Ketone", "Aldehyde"], "correctAnswer": 0 },
        { "question": "What is the shape of a molecule with sp2 hybridization?", "options": ["Linear", "Tetrahedral", "Trigonal planar", "Octahedral"], "correctAnswer": 2 },
        { "question": "Which gas law relates the volume of a gas to the number of moles?", "options": ["Boyle's Law", "Charles's Law", "Avogadro's Law", "Ideal Gas Law"], "correctAnswer": 2 },
        { "question": "What is the pH of a neutral solution?", "options": ["1", "7", "14", "0"], "correctAnswer": 1 },
        { "question": "Which element is a noble gas?", "options": ["Oxygen", "Helium", "Chlorine", "Sodium"], "correctAnswer": 1 },
        { "question": "What is the product of the combustion of a hydrocarbon?", "options": ["CO2 and H2O", "CO and H2", "O2 and H2", "CH4 and O2"], "correctAnswer": 0 },
        { "question": "Which type of reaction absorbs heat?", "options": ["Exothermic", "Endothermic", "Catalytic", "Redox"], "correctAnswer": 1 },
        { "question": "What is the molecular geometry of NH3?", "options": ["Linear", "Tetrahedral", "Trigonal pyramidal", "Bent"], "correctAnswer": 2 },
        { "question": "Which compound is an alkene?", "options": ["C2H6", "C2H4", "C2H2", "CH4"], "correctAnswer": 1 },
        { "question": "What is the role of a buffer solution?", "options": ["Increases pH", "Resists pH change", "Decreases pH", "Neutralizes acid"], "correctAnswer": 1 },
        { "question": "Which gas is produced during the reaction of a metal with acid?", "options": ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], "correctAnswer": 1 },
        { "question": "What is the oxidation state of iron in Fe2O3?", "options": ["+2", "+3", "+4", "+6"], "correctAnswer": 1 },
        { "question": "Which functional group is present in ketones?", "options": ["-OH", "-CHO", "-CO-", "-COOH"], "correctAnswer": 2 },
        { "question": "What is the general formula for alkenes?", "options": ["CnH2n", "CnH2n+2", "CnH2n-2", "CnHn"], "correctAnswer": 0 },
        { "question": "Which acid is present in lemon?", "options": ["Acetic acid", "Citric acid", "Lactic acid", "Hydrochloric acid"], "correctAnswer": 1 },
        { "question": "What is the product of the reaction between a metal and oxygen?", "options": ["Metal oxide", "Metal hydroxide", "Metal chloride", "Metal carbonate"], "correctAnswer": 0 },
        { "question": "What is the shape of a molecule with sp hybridization?", "options": ["Linear", "Tetrahedral", "Trigonal planar", "Bent"], "correctAnswer": 0 },
        { "question": "Which gas law relates pressure, volume, and temperature?", "options": ["Boyle's Law", "Charles's Law", "Ideal Gas Law", "Avogadro's Law"], "correctAnswer": 2 },
        { "question": "What is the pH of a strong base solution?", "options": ["0-2", "7", "10-14", "5-6"], "correctAnswer": 2 },
        { "question": "Which element is a transition metal?", "options": ["Sodium", "Iron", "Chlorine", "Helium"], "correctAnswer": 1 },
        { "question": "What is the product of the electrolysis of water?", "options": ["H2 and O2", "CO2 and H2O", "N2 and O2", "CH4 and O2"], "correctAnswer": 0 },
        { "question": "Which type of reaction involves the transfer of electrons?", "options": ["Acid-base", "Redox", "Precipitation", "Neutralization"], "correctAnswer": 1 },
        { "question": "What is the molecular geometry of CH4?", "options": ["Linear", "Tetrahedral", "Trigonal pyramidal", "Bent"], "correctAnswer": 1 },
        { "question": "Which compound is an alkyne?", "options": ["C2H6", "C2H4", "C2H2", "CH4"], "correctAnswer": 2 },
        { "question": "What is the role of Le Chatelier's principle?", "options": ["Predicts equilibrium shifts", "Increases reaction rate", "Changes products", "Absorbs heat"], "correctAnswer": 0 },
        { "question": "Which gas is produced during the fermentation of sugar?", "options": ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], "correctAnswer": 1 },

        // Physics (40 MCQs)
        { "question": "What is the unit of angular displacement?", "options": ["Meters", "Radians", "Seconds", "Newtons"], "correctAnswer": 1 },
        { "question": "Which law states that force equals mass times acceleration?", "options": ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Conservation"], "correctAnswer": 1 },
        { "question": "What is the terminal velocity of a falling object?", "options": ["Initial velocity", "Constant maximum velocity", "Minimum velocity", "Zero velocity"], "correctAnswer": 1 },
        { "question": "What is the formula for wave speed?", "options": ["v = f / λ", "v = f λ", "v = λ / f", "v = 1 / (f λ)"], "correctAnswer": 1 },
        { "question": "What is the first law of thermodynamics?", "options": ["Energy conservation", "Entropy increase", "Heat transfer", "Work done"], "correctAnswer": 0 },
        { "question": "What is the unit of electric field intensity?", "options": ["N/C", "V/m", "Both a and b", "J/C"], "correctAnswer": 2 },
        { "question": "What is the direction of the magnetic force on a positive charge moving in a magnetic field?", "options": ["Parallel to the field", "Perpendicular to the field", "Opposite to the field", "Random"], "correctAnswer": 1 },
        { "question": "What is the SI unit of power?", "options": ["Joule", "Watt", "Newton", "Pascal"], "correctAnswer": 1 },
        { "question": "Which type of wave requires a medium to propagate?", "options": ["Electromagnetic", "Mechanical", "Light", "Radio"], "correctAnswer": 1 },
        { "question": "What is the frequency of a wave with a wavelength of 2m and speed of 340 m/s?", "options": ["170 Hz", "340 Hz", "680 Hz", "1360 Hz"], "correctAnswer": 0 },
        { "question": "What is the principle behind the working of a transformer?", "options": ["Faraday's Law", "Ohm's Law", "Coulomb's Law", "Newton's Law"], "correctAnswer": 0 },
        { "question": "What is the value of acceleration due to gravity on Earth?", "options": ["9.8 m/s²", "8.9 m/s²", "10 m/s²", "5 m/s²"], "correctAnswer": 0 },
        { "question": "Which color has the longest wavelength in the visible spectrum?", "options": ["Violet", "Blue", "Green", "Red"], "correctAnswer": 3 },
        { "question": "What is the formula for kinetic energy?", "options": ["KE = mv", "KE = ½mv²", "KE = mgh", "KE = Fd"], "correctAnswer": 1 },
        { "question": "What is the unit of magnetic flux?", "options": ["Weber", "Tesla", "Henry", "Farad"], "correctAnswer": 0 },
        { "question": "Which law states that the current is proportional to voltage?", "options": ["Ohm's Law", "Faraday's Law", "Lenz's Law", "Bernoulli's Principle"], "correctAnswer": 0 },
        { "question": "What is the time period of a wave with a frequency of 50 Hz?", "options": ["0.02 s", "0.05 s", "0.1 s", "0.5 s"], "correctAnswer": 0 },
        { "question": "What is the effect of a capacitor in an AC circuit?", "options": ["Resists current", "Stores charge", "Increases voltage", "Blocks DC"], "correctAnswer": 1 },
        { "question": "What is the half-life of a radioactive substance if its activity drops to 25% in 12 days?", "options": ["3 days", "6 days", "12 days", "24 days"], "correctAnswer": 1 },
        { "question": "Which type of radiation has the highest penetrating power?", "options": ["Alpha", "Beta", "Gamma", "X-ray"], "correctAnswer": 2 },
        { "question": "What is the unit of momentum?", "options": ["kg·m/s", "N·s", "J·s", "W·s"], "correctAnswer": 0 },
        { "question": "Which law states that every action has an equal and opposite reaction?", "options": ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Conservation"], "correctAnswer": 2 },
        { "question": "What is the speed of sound in air at 0°C?", "options": ["331 m/s", "340 m/s", "343 m/s", "350 m/s"], "correctAnswer": 0 },
        { "question": "What is the formula for potential energy?", "options": ["PE = mv²", "PE = mgh", "PE = ½mv²", "PE = Fd"], "correctAnswer": 1 },
        { "question": "What is the unit of electric potential?", "options": ["Volt", "Ohm", "Ampere", "Farad"], "correctAnswer": 0 },
        { "question": "Which law explains the direction of induced current?", "options": ["Ohm's Law", "Faraday's Law", "Lenz's Law", "Coulomb's Law"], "correctAnswer": 2 },
        { "question": "What is the frequency of a wave with a wavelength of 4m and speed of 320 m/s?", "options": ["80 Hz", "160 Hz", "320 Hz", "640 Hz"], "correctAnswer": 0 },
        { "question": "What is the effect of an inductor in an AC circuit?", "options": ["Resists voltage", "Opposes change in current", "Stores charge", "Blocks AC"], "correctAnswer": 1 },
        { "question": "What is the half-life of a substance if its activity drops to 12.5% in 16 days?", "options": ["2 days", "4 days", "8 days", "16 days"], "correctAnswer": 2 },
        { "question": "Which type of radiation is deflected by a magnetic field?", "options": ["Gamma", "Beta", "Alpha", "Both b and c"], "correctAnswer": 3 },
        { "question": "What is the unit of capacitance?", "options": ["Farad", "Ohm", "Henry", "Tesla"], "correctAnswer": 0 },
        { "question": "Which law states that the total energy of an isolated system remains constant?", "options": ["First Law of Thermodynamics", "Second Law of Thermodynamics", "Third Law of Thermodynamics", "Zeroth Law"], "correctAnswer": 0 },
        { "question": "What is the speed of light in a vacuum?", "options": ["3 × 10^8 m/s", "3 × 10^6 m/s", "3 × 10^4 m/s", "3 × 10^2 m/s"], "correctAnswer": 0 },
        { "question": "What is the formula for angular velocity?", "options": ["ω = v/r", "ω = r/v", "ω = v + r", "ω = 1/r"], "correctAnswer": 0 },
        { "question": "What is the effect of temperature on the resistance of a conductor?", "options": ["Decreases", "Increases", "No effect", "Depends on material"], "correctAnswer": 1 },
        { "question": "Which type of mirror forms a virtual image for all object positions?", "options": ["Concave", "Convex", "Plane", "Both a and b"], "correctAnswer": 1 },
        { "question": "What is the unit of magnetic field strength?", "options": ["Tesla", "Weber", "Henry", "Farad"], "correctAnswer": 0 },
        { "question": "Which law explains the behavior of gases under varying pressure?", "options": ["Boyle's Law", "Charles's Law", "Gay-Lussac's Law", "All of these"], "correctAnswer": 0 },
        { "question": "What is the frequency of a wave with a period of 0.01 s?", "options": ["10 Hz", "100 Hz", "1000 Hz", "0.01 Hz"], "correctAnswer": 1 },
        { "question": "What is the effect of a resistor in a circuit?", "options": ["Increases current", "Reduces current", "Stores energy", "Produces voltage"], "correctAnswer": 1 },

        // English (10 MCQs)
        { "question": "What is the purpose of scanning a text?", "options": ["To read every word", "To answer short questions quickly", "To memorize the text", "To write a summary"], "correctAnswer": 1 },
        { "question": "Which tense is used for ongoing actions?", "options": ["Past Perfect", "Present Continuous", "Future Simple", "Past Simple"], "correctAnswer": 1 },
        { "question": "What is a synonym for 'happy' with a stronger emotion?", "options": ["Glad", "Ecstatic", "Content", "Pleased"], "correctAnswer": 1 },
        { "question": "Which punctuation mark is used to indicate possession?", "options": ["Comma", "Apostrophe", "Period", "Colon"], "correctAnswer": 1 },
        { "question": "What is the correct use of passive voice in this sentence: 'The room was cleaned'?", "options": ["Incorrect", "Correct", "Needs active voice", "Needs future tense"], "correctAnswer": 1 },
        { "question": "Which part of speech is 'quickly'?", "options": ["Noun", "Verb", "Adverb", "Adjective"], "correctAnswer": 2 },
        { "question": "What is the correct plural form of 'child'?", "options": ["Childs", "Children", "Childes", "Childen"], "correctAnswer": 1 },
        { "question": "Which sentence uses the correct subject-verb agreement?", "options": ["She walk to school.", "They walks to school.", "He walks to school.", "We walk to school."], "correctAnswer": 2 },
        { "question": "What is the function of a preposition?", "options": ["Shows action", "Links nouns or pronouns", "Describes a noun", "Connects clauses"], "correctAnswer": 1 },
        { "question": "Which sentence is in indirect speech?", "options": ["She said, 'I am tired.'", "She said that she was tired.", "She says, 'I am tired.'", "She will say, 'I am tired.'"], "correctAnswer": 1 },

        // Logical Reasoning (10 MCQs)
        { "question": "If all A are B, and some B are C, what can be concluded?", "options": ["All A are C", "Some A are C", "No A are C", "Cannot be determined"], "correctAnswer": 3 },
        { "question": "What comes next in the series: 2, 4, 6, 8?", "options": ["9", "10", "12", "14"], "correctAnswer": 1 },
        { "question": "If P implies Q, and Q is true, what can be said about P?", "options": ["P is true", "P is false", "P may be true or false", "Q implies P"], "correctAnswer": 2 },
        { "question": "A statement says: 'All cats are mammals.' Which option logically follows?", "options": ["All mammals are cats", "Some mammals are cats", "No cats are mammals", "Some cats are not mammals"], "correctAnswer": 1 },
        { "question": "If today is Sunday, what day will it be after 3 days?", "options": ["Monday", "Tuesday", "Wednesday", "Thursday"], "correctAnswer": 2 },
        { "question": "If some P are Q, and no Q are R, what can be concluded?", "options": ["Some P are R", "No P are R", "All P are R", "Cannot be determined"], "correctAnswer": 1 },
        { "question": "What comes next in the series: 1, 3, 6, 10?", "options": ["12", "13", "15", "16"], "correctAnswer": 2 },
        { "question": "If all M are N, and all N are O, what can be concluded?", "options": ["Some M are O", "All M are O", "No M are O", "Some N are M"], "correctAnswer": 1 },
        { "question": "If X is greater than Y, and Y is greater than Z, what is true?", "options": ["X < Z", "X > Z", "X = Z", "Y > X"], "correctAnswer": 1 },
        { "question": "If today is Monday, what day will it be after 7 days?", "options": ["Tuesday", "Wednesday", "Monday", "Sunday"], "correctAnswer": 2 }
    ];